name: Publish

on:
    push:
        branches:
            - master

jobs:
    Deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'

            - name: Run npm install
              run: npm ci

            - name: Build
              run: |
                  npm run build

            - name: Commit changes
              uses: EndBug/add-and-commit@v4
              with:
                  author_name: cc-open-source-bot
                  author_email: opensource@creativecommons.org
                  message: "Deploy site"
                  add: "./docs"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
